### ISSUE TITLE
GDAL master branch builds in CI require CMake

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Fiona#1061]
I'm pretty sure this explains the failures.

**Comment by rbuffat** [comment]
https://gdal.org/development/rfc/rfc84_cmake.html


> Add CMake as a new build system, and formally deprecate GNUmakefile and NMake base file systems. Users and packagers are encouraged to switch to CMake and actively report (and help fixing) issues the find in the process. GDAL 3.5.x point releases will be used to address reported issues.
>
> ==> Target: GDAL 3.5 / May 2022
> Completely remove GNUmakefile and NMake base file systems, and make CMake the only build system in GDAL source tree.
> 
> ==> Target: GDAL 3.6 / November 2022

**Comment by MaxLenormand** [comment]
We've been having issues since ~4 days with our CI pipelines, which use `GDAL`, `geopandas` and `proj` that all suddenly stopped working. 

Rolling back `fiona` to `1.8.20` made our tests pass. It was in our direct dependency lists, but now is. 

Not sure if this is related, just wanted to point this out if anybody else was facing this.

**Comment by rbuffat** [comment]
@MaxLenormand Unless you are compiling GDAL master your issue is most likely not related to this issue.  

Most likely your issue is related to that Fiona 1.8.21 does not ship binary wheels for Python 3.6 (Python 3.6 reached it's end of life last year https://www.python.org/dev/peps/pep-0494/#schedule-last-security-only-release).

**Comment by sgillies** [comment]
@MaxLenormand Please follow up at https://github.com/sgillies/fiona-wheels/issues/24 if you like. I'm going to delete your comments here as they are irrelevant to the CMake issue.

**Comment by sgillies** [comment]
Resolved.
