### ISSUE TITLE
date could not be parsed from gpx

### ISSUE THREAD

**Issue by arist0v** [Toblerity/Fiona#1252]
Hello, i got an issue during the creation of a fiona item from a .gpx file:

Behavior:
```
Warning 1: Could not parse 2023 01 24 14:40:21 as a valid dateTime
```
then in properties no time field created

Expected behavior:
that the date get parsed and a datetime object return in time properties

i can parse  this date using dateutil, so this date format could be supported.

```
parse('2023 01 24 14:40:21')
```

also, replacing the date by 2023-01-24 fix the issue (but for now can be done from the gpx file directly)

so there must be a way to enable parsing date without dash in it

**Comment by rbuffat** [comment]
@arist0v Would it be possible to provide the gpx file?

**Comment by arist0v** [comment]
Is there a way to send it to you privately?

**Comment by rbuffat** [comment]
You could check yourself if the `time` elements of the GPX file are in ISO8601 format (e.g. "2016-06-17T23:41:03Z"). The error message indicates that they are not. In this case, the GPX file is not valid and there is nothing we can do in Fiona, as the GDAL GPX driver will not be able to read this dataset.

**Comment by arist0v** [comment]
there is the trackptoint from the gpx:
```
<trkpt lat="50.307871029" lon="-77.299793288">
        <ele>269.307</ele>
        <time>2023-02-23T03:31:18Z</time>
      </trkpt>
```

**Comment by rbuffat** [comment]
Which element contains `2023 01 24 14:40:21`?

**Comment by arist0v** [comment]
sorry i think i pasted the wrong one:

```
<?xml version="1.0" encoding="UTF-8"?>
<gpx xmlns="http://www.topografix.com/GPX/1/1"  creator= "GSF Outils" version="1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.garmin.com/xmlschemas/GpxExtensions/v3 http://www.garmin.com/xmlschemas/GpxExtensions/v3/GpxExtensionsv3.xsd" > 

<trk>
         <name>Tracklog</name>
<extensions>
<gpxx:TrackExtension  xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3">
<gpxx:DisplayColor>Black</gpxx:DisplayColor>
</gpxx:TrackExtension>
</extensions>
<trkseg>

<trkpt lat="48.9322764" lon="-79.3446446">
<ele>111.1111111</ele>
<time>2023 01 22 17:01:17</time>
</trkpt
```

there is the header and first trackpoint

**Comment by sgillies** [comment]
@arist0v Fiona delegates GPX parsing to this C library code: https://github.com/OSGeo/gdal/tree/master/ogr/ogrsf_frmts/gpx. Like @rbuffat says, GDAL/OGR expects the  `<time>` element to contain an `xsd:dateTime` https://www.w3.org/TR/xmlschema-2/#dateTime. The error you see comes from https://github.com/OSGeo/gdal/blob/master/ogr/ogrsf_frmts/gpx/ogrgpxlayer.cpp#L983, not from Fiona.

Your data isn't valid GPX and Fiona can't help.

I recommend looking at https://docs.python.org/3/library/xml.etree.elementtree.html#modifying-an-xml-file as a starting point for how to modify the XML so that it is valid GPX.

I'm going to close this issue, as we will continue to require valid GPX as input for Fiona.

**Comment by arist0v** [comment]
Thank yoy!
