### ISSUE TITLE
RuntimeWarning when using list on collection

### ISSUE THREAD

**Issue by bekozi** [Toblerity/Fiona#194]
I am getting ``RuntimeWarning``s about a potentially altered cursor when calling ``list`` on a freshly opened collection object. I put together a test case recreating the message: https://gist.github.com/bekozi/2005f589fe8a87233543#file-test_read_cursor_warning_fiona-py-L45. There may be a very good reason for this, but I can’t sort out why...

**Comment by rbuffat** [comment]
I implemented this feature a while ago. 

The reason for this warning is that the underlying ogr api does not guarantee for certain functions that the internal read cursor of the layer is modified. 

```
    records = []
    for f in source:
        records.append(f)
```

does not issue a runtime warning, while 

```
    records = list(source)
```

issues a runtime warning while list() executes the get_length function of the session, that calls the ogr function OGR_L_GetFeatureCount: http://www.gdal.org/ogr__api_8h.html#abfbba8f45edd5dc44ced91f9228f9124 (Note that some implementations of this method may alter the read cursor of the layer.)

I don't know how many of the drivers (currently or in the future) supported by fiona are in danger of this behavior. 

@sgillies
I could implement a patch that stores the index and only issues a warning if the read cursor actually was moved.
Probably this feature causes more confusion that it helps, thus it might also be removed. Or a test suite should be created to test the behavior of the OGR api for all supported drivers by fiona to check if one of them modifies the read cursor.

**Comment by sgillies** [comment]
@rbuffat let's do remove the warning.

I'm not quite sure what the warning in the docs about read cursor alteration means. There are formats for which OGR_L_GetFeatureCount must read entirely through the file to get the count (GeoJSON for example) and the cursor would be set back to the beginning afterwards. Is this what the docs warn about or is there something else?

**Comment by rbuffat** [comment]
@sgillies 
I interpret it the same way. From the documentation the following methods are affected: OGR_L_GetExtent
OGR_L_GetExtentEx
OGR_L_GetFeatureCount

The only thing that bothers me is if a driver modifies the read cursor this will lead to bugs that will be very nasty to find because from fionas documentation you will not be able to see that this is allowed behavior according to the OGR API. Then again, the need to get count or extent during an iteration is not that likely to happen.

**Comment by sgillies** [comment]
@rbuffat I had hoped we could make this a "simple" documentation problem as with Python [file objects](https://docs.python.org/2/library/stdtypes.html#file.next) and just write that we can't mix `read()` and other access forms. But the variety of GDAL/OGR format drivers is a more complicated situation.

What would you think about warning when `bounds()` or `__len__()` are called when there is an active session and the active format is one that doesn't support random access? Tell the user that their position in the collection may be altered at that time?

**Comment by rbuffat** [comment]
@sgillies
an active session would probably be defined as at least one call to OGR_L_GetNextFeature(). A call to get OGR_L_GetFeature() would reset an active sessions (interrupts OGR_L_GetNextFeature). 

I'm not sure that this behavior is dependent on support for random access, because technically a driver could just restore the state after a scan of the data. That would be another reason for tests for this behavior. But as the implementation of drivers could change between ogr versions, this may be a bit complicated to test.

**Comment by bekozi** [comment]
For what it's worth, the fix works on my end. Also thanks for the explanations.
