### ISSUE TITLE
Make fio-info output useful to fio-cat

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Fiona#210]
Specifically: make possible the following.

``` bash
$ fio cat --bbox "`fio info --bounds file2.shp`" file1.shp
```

Or/and let the `--bbox` take paths to datasets, like

``` bash
$ fio cat --bbox file2.shp file1.shp
```

We're already doing with with `--dst_crs` and `--src_crs` and dataset paths in Rasterio. What I'm looking for is some discussion and consensus on whether this is a pattern we want to spread or not.

**Comment by geowurster** [comment]
@sgillies Just had a light need for `fio cat --bounds` to see how many points appear inside a rectangle.  Have you given this more thought?  Passing the `--bounds` value to `fiona.open(bounds)` would be pretty straightforward and I don't think this needs to take a file since we have `$(fio info --bounds)`.

If this sounds good I can put together a PR.

**Comment by geowurster** [comment]
Ah just found the `--bbox` flag.  Would be nice to be able to use `fio info` though.

**Comment by sgillies** [comment]
It would. In other places, we're accepting one of 

1. `w, s, e, n`
2. `w s e n`
3. `[w, s, e, n]`

This might be the right time to make this a standard option consistent across commands.

**Comment by geowurster** [comment]
@sgillies I like `--bounds w s e n` since it matches the `bounds` property, and seems to be what everyone has been using for the more recent CLI additions in `rio / fio`.  We can cover the 4 parameter options with the callback below (with some cleanup and self-intersection handling), and the `w,s,e,n` case can be handled with plenty of different unix tools to replace the commas with spaces.

```python
def _cb_bounds(ctx, param, value):

    v = ' '.join(value)
    try:

        bounds = tuple(map(float, re.findall(r"[-+]?\d*\.\d+|\d+", v)))
        assert len(bounds) is 4
        return bounds

    except Exception:
        raise click.BadParameter("Could not parse bounds: {}".format(' '.join(value)))
```

**Comment by sgillies** [comment]
Closing. We have this option: `fio cat --bbox $(fio info tests/data/coutwildrnp.shp | jq -c '.bounds') tests/data/coutwildrnp.shp`
