### ISSUE TITLE
Error with crs

### ISSUE THREAD

**Issue by bidhya** [Toblerity/Fiona#324]
The following command shows an attribute error
import fiona
fiona.crs.from_epsg(4269)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-f23d3f37e80b> in <module>()
      1 import fiona
----> 2 fiona.crs.from_epsg(4269) #(4326)

AttributeError: 'module' object has no attribute 'crs'

But when I do something related to crs, that error disappears, for example
from fiona.crs import from_epsg

Now the line of code works fine
print fiona.crs.from_epsg(4326)
{'init': 'epsg:4326', 'no_defs': True}

Can you please check what is the issue with Fiona here. It seems import fiona is not correctly importing the crs attribute. Am I missing something here?

I am on Windows with 32 bit python 2.7 with Fiona version 1.6.3

**Comment by micahcochran** [comment]
```Python
>>> import fiona.crs
>>> fiona.crs.from_epsg(4269)
{'init': 'epsg:4326', 'no_defs': True}
```
Is another way of doing what you want to do.

Are you saying that you expect `import fiona` to import all fiona "submodules" such as fiona.crs?

**Comment by bidhya** [comment]
thank you micahcochran, the approach you mentioned works correctly.

But yes, I was expecting import `import fiona` to expect  all submodules such as fiona.crs.

**Comment by geowurster** [comment]
@bidhya The `crs` module must be explicitly imported before it can be used, so the solution is to do:

```python
import fiona.crs
print(fiona.crs.from_epsg(4326)
```

I think you need to re-examine your example.  Your first example shouldn't work because you have not yet imported `fiona.crs`, but your second example should _also_ fail because you have only imported the `from_epsg()` function and not `fiona` _or_ the `crs` module.

Your second example should trigger an exception like:

```console
$ python
>>> from fiona.crs import from_epsg
>>> print(fiona.crs.from_epsg(4269))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'fiona' is not defined
```

however I suspect you are testing these two examples in the same session like this:

```console
$ python
>>> import fiona
>>> fiona.crs.from_epsg(4269)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'crs'
>>> from fiona.crs import from_epsg
>>> print(fiona.crs.from_epsg(4326))
{'init': 'epsg:4326', 'no_defs': True}
```

In this case the second import statement is also importing the `crs` module since you already did `import fiona`.  To be honest this is the first time I have been exposed to this specific import behavior and I'm not entirely sure how Python is resolving `fiona.crs` in the last part of the second example.  The real solution is to do:

```python
import fiona.crs
print(fiona.crs.from_epsg(4326)
```

I'll close this since it isn't a bug.

**Comment by bidhya** [comment]
Thank you for clarification @geowurster 
I didn't know that `crs` module need explicit import. Still I am not sure why such a behavior was adopted for `crs`

**Comment by geowurster** [comment]
@bidhya This is pretty typical of larger projects that can logically be split into smaller parts.  From an end-user's standpoint the big benefits are that import times can be significantly faster and the entire package won't break if a bug is introduced that only affects one submodule.  To let users access `fiona.crs` without having to explicitly import the submodule we effectively import it for you in `fiona/__init__.py`, but that means that it is _always_ imported whether or not you need it, so it introduces a bit of overhead.  Some modules are more expensive to import than others so the overhead adds up and can become a problem when trying to develop really fast utilities.

If we break a submodule that is imported in `__init__.py` that you don't use, `fiona` as a whole becomes unusable because it can't get past importing the broken submodule, even though the code you want to use was not touched at all.

If you are not already aware, `fiona.open(crs='EPSG:4326')` works, among a [few other representations](https://github.com/Toblerity/Fiona/blob/master/fiona/__init__.py#L118-L128).

**Comment by micahcochran** [comment]
@geowurster After your explanation, that design choice makes a whole lot more sense.   Thank you!
