### ISSUE TITLE
Schema must be known in order to open ESRI shapefile file with write permission

### ISSUE THREAD

**Issue by Jwely** [Toblerity/Fiona#335]
The following command returns `fiona.errors.SchemaError: no schema` 
``` python
    with fiona.open(input_shp, 'w', driver="ESRI Shapefile") as shp:
        print(shp)
```

I find the easiest work around for this is to open the shapefile with only read access first, read the schema, close it, then open with write permissions and the schema:

```python
    with fiona.open(input_shp) as shp:
        schema = shp.schema
    with fiona.open(input_shp, 'w', driver="ESRI Shapefile", schema=schema) as shp:
        print(shp)
```

This seems like a clunky workaround for something that should be straightforward, open a file, read its existing schema and be prepared to modify it, write new data, etc. Am I missing something obvious?

**Comment by geowurster** [comment]
@Jwely In case you are not aware, it looks like you want to update `input_shp` in place, which Fiona does not support, so the workflow you outlined _**will delete `input_shp`**_.

Fiona seeks to use Pythonic idioms wherever possible to be more familiar to developers.  `fiona.open()` behaves like Python's `open()`, which when invoked with `mode='w'` silently clobbers the file if it already exists on the first `write()`.

The behavior you describe is intentional and removes any ambiguity about what happens when writing to a path that already exists.  It would be confusing if an existing output file could be opened in write mode and have its schema available _until_ the first `write()` operation.

You probably want something more like:

```python
import fiona

with fiona.open(input_shp) as src, fiona.open(output_shp, 'w', **src.meta) as dst:
    for feature in src:
        # do something
        dst.write(feature)
```

**Comment by Jwely** [comment]
understood, thanks
