### ISSUE TITLE
Add --layer option to fio-cat

### ISSUE THREAD

**Issue by sgillies** [Toblerity/Fiona#349]
To allow access to layers within a file GDB, etc.

**Comment by smnorris** [comment]
Thanks. This seemed trivial at first so I was happy to take it on before I made the comment in the other thread. I started on the `cli-files` branch, just copying the patterns from `info` and `load`... but of course `cat` is concatenate!

This clearly doesn't work:  `fio cat input.gdb --layer inlayer1 input.gdb --layer inlayer2` 

So maybe a comma separated list is the way to go? 
`fio cat input.gdb input.gdb --layers "inlayer1,inlayer2"`
But then handling a mix of multi and single layer input files needs to be considered.

**Comment by sgillies** [comment]
@smnorris as you can see, multi-layer files haven't been our our radar. Let's take of care them now!

The usage snippet above is a lot like that of [`rio-stack`](https://github.com/mapbox/rasterio/blob/master/docs/cli.rst#stack). What would you think about adapting that? Simplest usage would be 

`fio cat input1.gdb --layer "1.a"`

Two layers from a single input:

`fio cat input1.gdb --layer "1.a,1.b"`

Five layers from two inputs:

`fio cat input1.gdb --layer "1.a,1.b" input2.gdb --layer "2.a,2.c,2.z"`

**Comment by smnorris** [comment]
👍  
I didn't realize it was possible to specify options in between the input layer args, I've only scratched the surface of `click`.

**Comment by geowurster** [comment]
@smnorris A click callback will be useful here too.  Something like:

```python
from collections import defaultdict

import click

def _cb_layer(ctx, param, value):

    out = defaultdict(list)
    for raw in value:
        for v in raw.split(','):
            ds, name = v.split('.')
            out[ds].append(name)

    return out


@click.option('--layer', callback=_cb_layer)
```

to process the CLI values like:

```python
cli_values = ["1.a,1.b", "2.a,2.c,2.z"]
print(_cb_layer(None, None, cli_values))
```

so in the function you get:

```python
{
    '1': ['a', 'b'],
    '2': ['a', 'c', 'z']
}
```

**Comment by smnorris** [comment]
It seems tricky to get consistency between the various layer and path indexing systems:
- `rio stack --bidx`:  1 based indexing
- `fio info --layer`: 0 based indexing
- proposed `fio cat --layer` syntax: 1 based index for the paths/files, and I think layer index support would be nice so `fio cat --layer` is consistent with `fio info --layer`

But then we get this:

`fio cat input1.gdb --layer "1.0, 1.1"` 

Works fine, but a bit odd.

I like a zero based index because of the beauty of `fio ls`. 
But I like consistency even more, maybe `fio info --layer` and `fio cat --layer` should use 1 based indexes throughout? Or maybe supporting indexing of layers in `fio cat --layer` is a step too far.

**Comment by geowurster** [comment]
Closed by https://github.com/Toblerity/Fiona/pull/354.
