### ISSUE TITLE
Desire for vsis3 in Fiona?

### ISSUE THREAD

**Issue by youngpm** [Toblerity/Fiona#425]
Any desire for such a feature akin to what rasterio has? Would be happy to poke at it!

**Comment by sgillies** [comment]
Yes, definitely. The feature is mostly implemented already, in GDAL, so that if `self.path = "/vsizip/vsicurl/htttp://example.com/myzip.zip/myshape.shp"` (at https://github.com/Toblerity/Fiona/blob/master/fiona/collection.py#L88) it just works. What's left to do is modify `vsi_path()` and add the AWS credential configuration (using boto3 as in Rasterio).

You've probably noticed this already, but multi-file formats like the shapefile must be zipped or otherwise archived, with zip being the best choice.

A problem is that to avoid an API change for `vsi_path()` and `fiona.open()` we're going to need to create a new URI scheme (maybe several schemes) for zipped files on S3. GDAL uses a device file-like syntax (for example `/vsizip/vsicurl/`), but we're using URIs to identify resources.

What would you think about `zip+s3` and `zip+https`? The `+` is valid in a URI scheme whereas `:` is not (see `zip:http` in https://commons.apache.org/proper/commons-vfs/filesystems.html).

Currently, `fio info zip:///Users/seang/code/Fiona/tests/data/coutwildrnp.zip` gets the first dataset in a zipfile, kind of a shortcut. It would be great if `fio info zip+s3://mybucket/coutwildrnp.zip` did the same for a zipfile on S3.

**Comment by youngpm** [comment]
Alright, I'll start working on this.  I'll submit the PR's early for working out any kinks!

**Comment by sgillies** [comment]
Closed by #426.
