### ISSUE TITLE
Number formatting is not consistent among drivers

### ISSUE THREAD

**Issue by galak75** [Toblerity/Fiona#528]
According to the [documentation](http://toblerity.org/fiona/manual.html#format-drivers-crs-bounds-and-schema), a schema can be provided when writing records to a file.

e.g.:
```
    def _write_collection(self, driver):
        writing_schema = {
            'geometry': 'Point',
            'properties': [('integer', 'int'), ('one_digit', 'float:15.1')]
        }

        with fiona.open(
                self.filename,
                "w",
                driver=driver,
                schema=writing_schema,
                crs='epsg:4326',
                encoding='utf-8'
        ) as c:
            c.writerecords([
                {
                    'geometry': {'type': 'Point', 'coordinates': (0.0, 0.1)},
                    'properties': {'integer': 12.22, 'one_digit': 12.22}
                },
                {
                    'geometry': {'type': 'Point', 'coordinates': (0.0, 0.2)},
                    'properties': {'integer': 12.88, 'one_digit': 12.88}
                }
            ])
```

Unfortunately, all drivers do not behave the same:

- `ESRI Shapefile` truncates values to get an `int`, and rounds values to limit digits numbers (`float:15.1`)
- `GeoJSON` also truncates values to get an an `int`, but does not respect float formatting (`float:15.1`)

2 questions : 

1. Is it possible to make `GeoJSON` driver respect float formatting?
1. Shouldn't we have a common behavior for `int` and `float:15.1` types? (either rounding or truncating)

**Comment by sgillies** [comment]
@galak75 The float formatting is done by GDAL/OGR and I'm inclined to let it continue as it is. As you've noticed, support for field widths and decimal precision is uneven in GDAL/OGR. As far as I can tell, the OGR concepts of field width and precision derive more from the designs of older spatial data formats than from the desire to have first class support for decimals (like Python's decimal modules).

The integer conversion is done by Fiona and only exists to trigger exceptions when we mistakenly try to copy non-numeric values to numeric fields, so that we don't get an exception deeper in OGR. Calling `int(round())` instead of `int()` goes too far for me. 

Fiona schemas aren't intended to validate and coerce your data into conformation. Their only purpose is to tell OGR how to format already-conforming data appropriately for a specific spatial data format. It only works at the OGR <-> data file interface.

Said another way: Fiona doesn't have a schema framework for you to use in your own application. When you serialize a feature using `collection.writerecords()`, it is assumed that your data already fits an application schema, and the `schema` keyword argument you pass to `fiona.open()` is *only* a representation of that application schema in terms that Fiona and OGR understand.

**Comment by galak75** [comment]
I have written some unit tests to show the drivers current behavior.
Please let me know if you want me to create a pull request with them

**Comment by galak75** [comment]
@sgillies thanks a lot for your very clear explanations. It makes sense.

I just want to provide some more context:
I'm currently using Geopandas, and having a "year" property in my data. This "year" value is sometimes missing, which leads Pandas to promote this Series type from int to float (see [Pandas FAQ](https://pandas.pydata.org/pandas-docs/stable/gotchas.html#nan-integer-na-values-and-na-type-promotions)); Then `2018` becomes `2018.0`
Having Fiona calling `int()` for this property solves this problem when serializing data to any file

For decimals support, I understand I should:

- either look into GDAL/OGR library and submit some change request on `GeoJSON` driver (written in C?)
- or format my float column directly in my GeoSeries or GeoDataframes before serializing

Is that correct?

**Comment by sgillies** [comment]
@galak75 Correct. Another workaround is to avoid GDAL/OGR's GeoJSON driver. It's not better than `json.dumps()` and I find some of its assumptions and constraints limiting. Fiona's fio-cat program, for example, bypasses the GeoJSON driver, and I usually do the same kind of thing in programs at work. It would be much less work to customize `json.JSONEncoder` to add support for decimals.

**Comment by galak75** [comment]
@sgillies Thx
Last question : do you want me to submit a pull request with additional unit tests (eventually without the decimals part) ? (see https://github.com/galak75/Fiona/commit/d3d74aa6e7c41c5204879314cbb202ed033cd852)

**Comment by sgillies** [comment]
@galak75 sure!
