### ISSUE TITLE
Possible race condition when reading a dataset from S3

### ISSUE THREAD

**Issue by mccarthyryanc** [Toblerity/Fiona#579]
I'm getting a `DriverError` when using fiona and joblib to read from a GPKG on S3:

```
/home/ubuntu/miniconda/envs/test-env/lib/python3.6/site-packages/fiona/_shim.cpython-36m-x86_64-linux-gnu.so in fiona._shim.gdal_open_vector()

DriverError: AWS_SECRET_ACCESS_KEY configuration option not defined
```
Example:
```python
import fiona
from joblib import Parallel, delayed

def get_count(extent):
     with fiona.open('s3://bucketname/testfile.gpkg','r', layer='layername') as ds:                      
         return len([i for i in ds.filter(bbox=extent)])
with Parallel(n_jobs=4, verbose=10) as parallel:
     results = parallel(delayed(get_count)(i) for i in [extent]*1000)
```

I think this is a race condition because I can make the above code work by adjusting `n_jobs` and `[extent]*1000`. I'm not familiar to how fiona grabs AWS credentials, but this does look like a [common issue](https://stackoverflow.com/questions/36287720/boto3-get-credentials-dynamically#36291428) with boto3

## System Specs

Ubuntu 16.04
Fiona 1.8a2
Python 3.6

Installed via pip within a conda env:
```bash
conda create -n test-env gdal=2.2* python=3.6 -c conda-forge
conda activate test-env
pip install git+https://github.com/Toblerity/Fiona.git
```

**Comment by sgillies** [comment]
@mccarthyryanc 

Curl fetches geopackage bytes using the AWS HTTP API and gets auth headers from the current thread's global GDAL configuration. Fiona sets the configuration using credentials obtained from a boto session (via AWS config file or environment variables, see https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html for details). Currently, there is a session created every time `fiona.open` is called on an S3 resource. If you application is getting credentials from a file or URL, you are probably more likely to hit the race condition than if it has credentials in environmental variables.

Fiona's AWS support is a little behind Rasterio's and we're going to improve it for 1.8. Meanwhile, I think you'll need to rework your code a bit. I don't think joblib and GDAL are very well suited for each other.

What I do in a few different concurrent Rasterio applications is use `multiprocessing.Pool` (https://docs.python.org/3.6/library/multiprocessing.html#module-multiprocessing.pool) and use its initializer argument to ensure that `rasterio.open()` is called only once for each pool worker before they begin their jobs.

https://github.com/mapbox/rio-mbtiles/blob/master/mbtiles/scripts/cli.py#L179
https://github.com/mapbox/rio-mbtiles/blob/master/mbtiles/__init__.py#L19

I believe that in your case you may want to try a thread pool instead of a process pool (because of the HTTP requests). In https://stackoverflow.com/questions/3033952/threading-pool-similar-to-the-multiprocessing-pool I learned that the multiprocessing module contains a thread pool class with a similar initializer. Could be worth a try.

**Comment by mccarthyryanc** [comment]
@sgillies , thanks for the feedback. I think joblib is using the `mutliprocessing` module, but you are probably right this it isn't initializing each worker properly. I'll try to set this up without joblib.

Another piece of possibly relevant info is that I am running this on an EC2 instance that has been assigned an IAM role, so no config file or environment variables. But, I'm assuming this still requires an HTTP request to a metadata service.
