### ISSUE TITLE
How i find my gdal include files and gdal libary

### ISSUE THREAD

**Issue by LimaGuilherme** [Toblerity/Fiona#600]
I install GDAL folowing your readme, 
but when i wanna install Fiona for windows, ask me for include path where GDAl include files and gdal libary.

in this command:

`$ python setup.py build_ext -I<path to gdal include files> -lgdal_i -L<path to gdal library> install --gdalversion 2.1`

my GDAL 1.11.4, released 2016/01/25
i'm using Windows 8.1 x64

where is my path to gdal include files and gdal libary?

**Comment by sgillies** [comment]
@LimaGuilherme I don't know what the paths are on your computer. Since there is no standard install location on Windows, they could be anywhere. You must search your computer for the gdal.h file. The directory containing it will be your `-I` path. Then you must search your computer for the gdal_i.lib file. The directory containing it will be your `-L` path.

I don't recommend installing Fiona from source on Windows. It is much easier to download the Anaconda distribution of Python and then install Fiona from https://anaconda.org/conda-forge/fiona.
