### ISSUE TITLE
Some tests do not use conftest.data_dir() to find test data

### ISSUE THREAD

**Issue by schwehr** [Toblerity/Fiona#616]
I'm setting up for a test infrastructure that gets the test data from somewhere not near the current working directory of the test.  It would be much easier to control this if everything consistently used conftest.data_dir().  `test_read_drivers.py` does not.  Here is what I ended up with:

```py
import logging
import os
import sys

import conftest
import pytest

import fiona
from fiona.errors import FionaValueError

def test_read_fail():
    filepath = os.path.join(conftest.data_dir(), 'coutwildrnp.shp')
    with pytest.raises(FionaValueError):
        fiona.open(filepath, driver='GeoJSON')
    with pytest.raises(FionaValueError):
        fiona.open(filepath, enabled_drivers=['GeoJSON'])


def test_read():
    filepath = os.path.join(conftest.data_dir(), 'coutwildrnp.shp')
    with fiona.open(filepath, driver='ESRI Shapefile') as src:
        assert src.driver == 'ESRI Shapefile'
    with fiona.open(filepath, enabled_drivers=['GeoJSON', 'ESRI Shapefile']) as src:
        assert src.driver == 'ESRI Shapefile'
```

**Comment by snorfalorpagus** [comment]
I agree that some consistency would be nice.

The `data_dir` function is actually a pytest fixture, so you can use it as below - you don't even need to `import conftest` for this to work:

```python
def test_read_fail(data_dir):
    filepath = os.path.join(data_dir, 'coutwildrnp.shp')
    with pytest.raises(FionaValueError):
        fiona.open(filepath, driver='GeoJSON')
    with pytest.raises(FionaValueError):
        fiona.open(filepath, enabled_drivers=['GeoJSON'])
```

@schwehr Would you be willing to make a PR to this effect?

**Comment by QuLogic** [comment]
This is made more complicated by the fact that many tests are still `unittest.TestCase`, and pytest does not apply fixtures to those.

**Comment by sgillies** [comment]
Done! I found the key in https://docs.pytest.org/en/latest/unittest.html#mixing-pytest-fixtures-into-unittest-testcase-subclasses-using-marks.

**Comment by QuLogic** [comment]
I'm not sure this is actually fixed, as when I try to run against an installed version, the fixtures cannot be found.

**Comment by landryb** [comment]
Same thing, on 1.8.1 all tests in `test_collection_legacy.py` fail:
```
Traceback (most recent call last):                                                                                                                            
  File "/usr/obj/ports/py-fiona-1.8.1/Fiona-1.8.1/tests/test_collection_legacy.py", line 17, in setUp                                                         
    self.c = fiona.open(self.path_coutwildrnp_shp, "r")                                                                                                       
AttributeError: 'ReadingTest' object has no attribute 'path_coutwildrnp_shp'  
```
dunno if a commit adressing this should be backported on top...

**Comment by sgillies** [comment]
@QuLogic @landryb how are you running the tests and with what version of pytest? The fiona-wheels project runs the tests using an installed wheel like this: https://github.com/sgillies/fiona-wheels/blob/master/config.sh#L255-L258. It copies the tests to another location so that local Python files aren't picked up.

**Comment by sgillies** [comment]
@landryb I'm happy to hear that OpenBSD packages exist!

I can't reproduce the test failures on my laptop (Ubuntu 18.04) or Travis CI. This may be a platform specific issue or it may have something to do with your Python path.

On my laptop and on Travis, I build and test the code within a virtual environment like this:

```
$ cd Fiona
$ pip install -r requirements-dev.txt
$ pip install -e .[test]
$ python -m pytest
```

`pip install -e .` is approximately equivalent to `python setup.py develop`. `python setup.py test` does something slightly different, I suspect.

**Comment by QuLogic** [comment]
When locally testing, I use `-e` which works all the time, since there's never multiple copies of things to confuse pytest.

On Fedora, we test the installed package, but the installed package is in a temporary buildroot. So `-e` is not really useful since we want to test the install, not some intermediary. Instead, `PYTHONPATH` is set to look in the temporary location. Because of the extensions, the problem that we run into is not about `conftest`, but rather that the source `fiona` directory comes first in the search path. So as a workaround, I delete the source `fiona`, which is basically the same as what you do on Travis.

So I don't seem to run into this issue anymore, either because there are never two copies of anything around to confuse pytest, or because of the other fixes that went in between the alpha and the final release.
