### ISSUE TITLE
PROPOSAL: Add ability to specify fields to load

### ISSUE THREAD

**Issue by snowman2** [Toblerity/Fiona#887]
Currently, you can define which fields to not load in using `ignore_fields`:
https://github.com/Toblerity/Fiona/blob/2c1cef667160e226f6ee5af1cbb0815d1295d5bf/fiona/collection.py#L37
https://github.com/Toblerity/Fiona/blob/2c1cef667160e226f6ee5af1cbb0815d1295d5bf/fiona/ogrext.pyx#L129

Thoughts on adding a parameter with a name like `fields` or `include_fields` where only these fields will be loaded in?

Currently in `geopandas` this is a feature that would be nice to add. However, doing so though the Fiona API (which would be preferable and more efficient) would require first opening the file and getting a list of fields and then removing the fields not in the list the user specified. Then, you would have to open the file again with the list of fields to ignore. 

Ref: https://github.com/geopandas/geopandas/pull/1383

cc: @brendan-ward

**Comment by snowman2** [comment]
Side note: I would be happy to implement this feature if the proposal is approved.

**Comment by ddileonardo** [comment]
This issue is marked as closed and the include_fields option is shown in the geopandas documentation as an option with fiona, but I do not think it works as intended. Every field is still included in the import as far as I can tell. Ignore_fields works as expected.

`sand = read_geodata(mmis, layer=sand_layer,mode='r', ignore_geometry=False,
                    include_fields=['Year', 'PercentSand', 'StudyID','SandUnitThickness','Area_feet','Volume_CY',
                                    'Comments','WebLink','Citation','EvaluationStage'])`
Result:
sand.columns
Index(['State', 'Year', 'GrainSize', 'MunsellColor', 'PercentSand',
       'PercentCarbonate', 'PctCarbonateSand', 'GlobalResourceID',
       'Resource_GlobalLinkID', 'SedAreaID', 'RuleID', 'Override', 'StudyID',
       'EvaluationStage', 'SandUnitThickness', 'Area_feet', 'Volume_CY',
       'Comments', 'PercentFines', 'SourceReport', 'WebLink', 'Citation',
       'SourceType', 'SHAPE_Length', 'SHAPE_Area', 'geometry'],
      dtype='object')
