### ISSUE TITLE
There is no support for binary files for Python3.9

### ISSUE THREAD

**Issue by benoitbesson** [Toblerity/Fiona#978]
This [link](https://pypi.org/project/Fiona/#files) only provides support for python3.8.
Is there a plan to provide binaries for python3.9 ?
Something like : Fiona-1.8.18-cp39-cp39-manylinux1_x86_64.whl=

I would be great !

Thanks,

Ben.

**Comment by valeriupredoi** [comment]
hey guys, just to add to this - `fiona` installs well in a `python=3.9` environment but a simple `import fiona` doesn't work, clearly because the current latest version doesn't work with `python=3.9`; if you guys can release a version compatible with py3.9 it would be awesome, in the meantime, I would recommend restricting the package requirements so it requires `python<3.9`:

```
(esmvalcore39) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValCore$ python -V
Python 3.9.0
(esmvalcore39) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValCore$ conda -V
conda 4.9.2
(esmvalcore39) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValCore$ conda list fiona
# packages in environment at /home/valeriu/miniconda3/envs/esmvalcore39:
#
# Name                    Version                   Build  Channel
fiona                     1.8.18                   pypi_0    pypi
(esmvalcore39) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValCore$ python testfiona.py
Traceback (most recent call last):
  File "/home/valeriu/ESMValCore/testfiona.py", line 1, in <module>
    import fiona
  File "/home/valeriu/miniconda3/envs/esmvalcore39/lib/python3.9/site-packages/fiona/__init__.py", line 86, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/home/valeriu/miniconda3/envs/esmvalcore39/lib/python3.9/site-packages/fiona/collection.py", line 11, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libgdal.so.26: cannot open shared object file: No such file or directory
```

Cheers :beer:

**Comment by valeriupredoi** [comment]
to follow-up my comment above, installing `fiona` from `conda-forge` rather than PyPi works well (`fiona=1.8.18`) so kudos for providing the `linux-64/fiona-1.8.18-py39h3573629_0` pack, if you guys could do the manylinux one for PyPi it'd be swell (as @benoitbesson points out). Cheers again!

**Comment by rbuffat** [comment]
@benoitbesson 
Yes, currently there are now wheels for Python 3.9. One of the reasons is that Fiona's wheels are built on travis, which recently reduced it's support for open source projects. Thus, it is currently a bit unclear how wheels will be built in the future https://fiona.groups.io/g/dev/topic/fiona_project_status_report/78346361?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,78346361

**Comment by rbuffat** [comment]
@valeriupredoi 
> clearly because the current latest version doesn't work with python=3.9

There are currently no issues known with Fiona and Python 3.9 and all tests run successful on the continuous integration.
 
This issue is about missing wheels for Python 3.9, which is a packaging issue and does not affect Fiona itself. In the future, please create a new issue for unrelated topics. 

You are mixing pip packages with conda. In general, you should avoid doing this: https://www.anaconda.com/blog/using-pip-in-a-conda-environment

**Comment by valeriupredoi** [comment]
@rbuffat cheers for your reply! I will open an issue, but I thought I'd save you guys one if I just posted the problem here. In a nutshell: if you have a package like ours, that needs dependencies from both conda and PyPi and a number of dependencies are to be found only on conda channels and not on PyPi, and conversely, other dependencies are pure Python on PyPi and not on conda,  you are kind of restricted to using a conda environment; what we do, we try to use the dependencies that are on PyPi (if they are both on conda and PyPi) because they tend to be more solid in terms of their dependency requirements and they don't break as often as the conda ones. `fiona` was one of them, until now - we used to install it from PyPi, in our package's conda virtual env, so are a bunch of others - having said that, `fiona` has issues with python=3.9 in a conda environment, when installed from PyPi, period. Please have a closer look at your new package on PyPi - in a conda env with nothing but python=3.9 as dep requirement:
```
(py39) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValCore$ python -V
Python 3.9.0
(py39) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValCore$ conda list fiona
# packages in environment at /home/valeriu/miniconda3/envs/py39:
#
# Name                    Version                   Build  Channel
fiona                     1.8.18                   pypi_0    pypi
(py39) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValCore$ python testfiona.py 
Traceback (most recent call last):
  File "/home/valeriu/ESMValCore/testfiona.py", line 1, in <module>
    import fiona
  File "/home/valeriu/miniconda3/envs/py39/lib/python3.9/site-packages/fiona/__init__.py", line 86, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/home/valeriu/miniconda3/envs/py39/lib/python3.9/site-packages/fiona/collection.py", line 11, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libgdal.so.26: cannot open shared object file: No such file or directory
```
the env has been contructed with this env file:
```yaml
---
name: py39
channels:
  - conda-forge

dependencies:
  - python=3.9
```
We will have to use the conda-forge package if this issue is not resolved, and it'd be a shame since we're trying to switch to the PyPi packages as much as possible (bar, of course, the ones that simply are not on PyPi). Cheers for your support! :beer:
